version: "3.1"
services:

  node:
    restart: unless-stopped
    image: node:15.14.0
    working_dir: /application
    container_name: nodejs
    volumes:
      - .:/application
    ports:
      - 3000:3000    
    entrypoint: [ "npm", "run", "dev" ]

  mongo:
    image: mongo:latest
    container_name: mongo-nodejs
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass_test
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: nodejs-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass_test
      ME_CONFIG_MONGODB_URL: mongodb://root:pass_test@mongo:27017/