version: "3.1"
services:

  nodejs:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
    ports:
       - 3000:3000    

  mongo:
    image: mongo:latest
    container_name: mongo-nodejs
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    volumes:
      - ./docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
  mongo-express:
    image: mongo-express
    container_name: nodejs-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/